GETDATE() --> DB Timestamp
CONVERT(NVARCHAR, L.DATUM_EIN, 121) --> DATE TO STRING
CONVERT(VARCHAR(8), GETDATE(), 112)	--> Date to YYYYMMDD
convert(DATETIME, '2018-05-01 00:00:00', 121) --> STRING TO DATE
DATEDIFF(SECOND, L.DATUM_EIN, L.DATUM_AUS) --> DATE GAP
SELECT DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()- 1), 0) --> Yesterday
DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE() - 7), 0) --> Last Monday
DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE() - 7), 5) --> Last Saturday
DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0) - 1 --> Last day of last month
SELECT DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 1, 0) as FirtDayPreviousMonthWithTimeStamp;
SELECT DATEADD(SS, -1, DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0)) as LastDayPreviousMonthWithTimeStamp;
