-- SELECT DATEADD(ss, -1, DATEADD(month, DATEDIFF(month, 0, getdate()), 0))

CREATE FUNCTION [dbo].[GET_LAST_MONTH_END] ()  
RETURNS int  
WITH EXECUTE AS CALLER  
AS  
BEGIN  
	 DECLARE @GET_LAST_MONTH_END int;
	 DECLARE @YYYY int;
	 DECLARE @MM int;
	 DECLARE @DD int;
	 DECLARE @DT DATETIME;	 
	 SET @DT = dateadd(MONTH,datediff(month,0,GETDATE()),0)-1;
	 SET @YYYY = YEAR(@DT);
	 SET @MM = MONTH(@DT);
	 SET @DD = DAY(@DT);
	 SET @GET_LAST_MONTH_END = @YYYY*10000 + @MM*100 + @DD;
	 RETURN(@GET_LAST_MONTH_END);
END;  
