CREATE FUNCTION [dbo].[GET_LAST_MONTH_START] ()  
RETURNS int  
WITH EXECUTE AS CALLER  
AS  
BEGIN  
	 DECLARE @LAST_MONTH_START int;
	 DECLARE @YYYY int;
	 DECLARE @MM int;
	 DECLARE @DD int;
	 DECLARE @DT DATETIME;	 
	 SET @DT = dateadd(MONTH,datediff(month,0,GETDATE()),0)-1;
	 SET @YYYY = YEAR(@DT);
	 SET @MM = MONTH(@DT);
	 SET @DD = 1;
	 SET @LAST_MONTH_START = @YYYY*10000 + @MM*100 + @DD;
	 RETURN(@LAST_MONTH_START);
END;  
